services:
  core:
    build:
      context: core
      dockerfile: Containerfile
    env_file:
      - core/.env
    volumes:
      - "./to-do:/data"
  mcp:
    build:
      context: mcp
      dockerfile: Containerfile
    depends_on:
      - core
