services:
  core:
    build:
      context: .
      dockerfile: app/core/Containerfile
    env_file:
      - app/core/.env
    volumes:
      - "knotwork-repo:/data"
  mcp:
    build:
      context: .
      dockerfile: app/mcp/Containerfile
    depends_on:
      - core
    ports:
      - 80:80
volumes:
  knotwork-repo:
    external: true
