services:
  core:
    build:
      context: .
      dockerfile: app/core/Containerfile
    env_file:
      - app/core/.env
    volumes:
      - "./to-do:/data"
  mcp:
    build:
      context: .
      dockerfile: app/mcp/Containerfile
    depends_on:
      - core
