FROM golang:1.26.3 AS build

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /bin/mcp ./app

FROM alpine

COPY --from=build /bin/mcp /bin/mcp

ENTRYPOINT [ "/bin/mcp" ]
